### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by divyangkhatri** [aglawson/Meta-Transactions#2]
Hello @aglawson 

I am using your relayerAddress "0x2A0d1f0EE9c5584b1694BCa16879423432770A52". Is it okay?

```
app-index.js:32 Error in send ether token transaction Error: execution reverted: "Ownable: caller is not the owner" (action="estimateGas", data="0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000204f776e61626c653a2063616c6c6572206973206e6f7420746865206f776e6572", reason="Ownable: caller is not the owner", transaction={ "data": "0x47153f82000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000001600000000000000000000000000e609351475788a03a7944cabe4a656762245a3a000000000000000000000000f8ec8f7f7d5ece27130227bd7846ef24e86e809100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002710000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000024a0712d680000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041c220b1395b6d07d07cd989bdb53e09ffa7058d6ddf319f82d85f1d59350580506a58f85976da27f479cf7f7d3fe332828f70d67ea0eaa8870e24a2123b80c8f81b00000000000000000000000000000000000000000000000000000000000000", "from": "0xF8eC8f7f7D5Ece27130227Bd7846ef24e86E8091", "to": "0x2A0d1f0EE9c5584b1694BCa16879423432770A52" }, invocation=null, revert={ "args": [ "Ownable: caller is not the owner" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.8.1)
    at makeError (errors.js:137:21)
    at getBuiltinCallException (abi-coder.js:119:70)
    at AbiCoder.getBuiltinCallException (abi-coder.js:216:16)
    at JsonRpcProvider.getRpcError (provider-jsonrpc.js:618:76)
    at eval (provider-jsonrpc.js:287:45)
```

Below is code snippet and getting error in the last line of code while calling "execute" function

```
  sendToken: async ({
      to,
      from,
      amount,
      privateKey,
      estimateGas,
      gasFee,
      contractAddress,
      fee,
    }) => {
      try {
        const wallet = new ethers.Wallet(privateKey);
        let walletSigner = wallet.connect(ethersProvider);
        const relayer = '0x2A0d1f0EE9c5584b1694BCa16879423432770A52';
        const forwarder = new ethers.Contract(relayer, abi, ethersProvider);
        const nonce = await forwarder.getNonce(from);
        console.log('nonecee', nonce);
        const abiCoder = new AbiCoder();
        let data = abiCoder.encode(['uint256'], [amount]);
        data = data.slice(2, data.length);
        const Req = {
          from: from,
          to: to,
          value: 0,
          gas: 10000,
          nonce: nonce,
          data: '0xa0712d68' + data,
        };

        let message = solidityPackedKeccak256(
          ['address', 'address', 'uint256', 'uint256', 'uint256', 'bytes'],
          [Req.from, Req.to, Req.value, Req.gas, Req.nonce, Req.data]
        );

        const arrayifyMessage = await getBytes(message);
        const flatSignature = await walletSigner.signMessage(arrayifyMessage);
        console.log('resultttt', flatSignature);
        //Private key
        const payPrivateKey =
          ''; // valid fee payer privateKey
        const feePayer = new ethers.Wallet(payPrivateKey, ethersProvider);
        const contract = new ethers.Contract(relayer, abi, ethersProvider);
        let result = await contract
          .connect(feePayer)
          .execute(Req, flatSignature);
        console.log('finalResuel', result);
```

**Comment by aglawson** [comment]
No, you should be deploying your own relayer contract. Only the owner of the contract has permissions to trigger the 'execute' function on the contract.
